// schema.js
// Defines the exact field structure for the 5 monitoring categories,
// matching the government template files field-for-field.

const BASIC_INFO_FIELDS = [
  { key: '計畫代碼', label: '計畫代碼', type: 'text', required: true,
    help: '格式為「英文代碼-四碼流水號」，例如 E-0001；如有延伸編碼請填 E-0001.1（請勿使用舊版三碼格式）' },
  { key: '書件案號', label: '書件案號', type: 'text',
    help: '共8碼：前7碼為數字，第8碼為英文大寫（若無可不填）' },
  { key: '書件名稱', label: '書件名稱', type: 'text', help: '請填寫完整書件名稱，勿使用簡易寫法' },
  { key: '執行現況', label: '執行現況', type: 'select',
    options: ['施工前', '施工中', '施工兼營運', '營運中'] },
  { key: '施工日期', label: '施工日期', type: 'date', help: '執行現況為施工中/施工兼營運時請務必填寫' },
  { key: '竣工日期', label: '竣工日期', type: 'date', help: '執行現況為施工兼營運/營運中時請填寫' },
  { key: '營運日期', label: '營運日期', type: 'date', help: '執行現況為施工兼營運/營運中時請務必填寫' },
  { key: '備註', label: '備註', type: 'textarea', help: '100字以內' },
];

// 檢測類別 option lists per category (from 環境監測填寫範本 資料辭典)
const CATEGORY_TYPE_OPTIONS = {
  air: ['大氣環境', '固定污染源', '移動污染源', '周界空氣品質', '室內空氣品質', '光污染'],
  water: ['飲用水', '自來水', '河川', '水庫', '海域海灘', '地下水', '水下噪音-打樁', '水下噪音-風場範圍', '污廢水', '回收水', '雨水'],
  geo: ['土壤品質', '土砂觀測', '土壤', '底泥品質', '毒化物質', '廢棄物'],
  noise: ['環境噪音', '道路交通噪音', '營建工程噪音', '公私場所噪音', '航空噪音', '低頻噪音', '振動'],
};

// 比較關係 is documented as ">, <, ND" only, but real completed filings also use
// free-text markers like "未檢測" (equipment failure) etc., so this is a text field
// with suggestions rather than a strict enum.
const COMPARE_SUGGESTIONS = ['>', '<', 'ND', '未檢測'];

const CATEGORIES = {
  air: {
    key: 'air',
    label: '空氣品質',
    sourceFile: '空氣品質監測填寫.xlsx',
    dataSheetName: '空品檢測項目',
    basicSheetName: '監測點基本資料',
    fields: [
      { key: '日期(起)', label: '日期(起)', type: 'date', required: true },
      { key: '時間(起)', label: '時間(起)', type: 'time' },
      { key: '日期(迄)', label: '日期(迄)', type: 'date' },
      { key: '時間(迄)', label: '時間(迄)', type: 'time' },
      { key: '採樣地點', label: '採樣地點', type: 'text' },
      { key: '座標系統', label: '座標系統', type: 'select', options: ['', '2', '3'],
        optionLabels: { '2': '2：WGS84', '3': '3：TWD97-TM2' } },
      { key: '採樣座標-經度 X', label: '採樣座標-經度 X', type: 'number' },
      { key: '採樣座標-緯度 Y', label: '採樣座標-緯度 Y', type: 'number' },
      { key: '場所編號', label: '場所編號', type: 'text' },
      { key: '採樣地點高度(公尺)', label: '採樣地點高度(公尺)', type: 'number' },
      { key: '污染物採樣高度(公尺)', label: '污染物採樣高度(公尺)', type: 'number' },
      { key: '管制編號', label: '管制編號', type: 'text' },
      { key: '煙道編號', label: '煙道編號', type: 'text' },
      { key: '檢測類別', label: '檢測類別', type: 'select', required: true, options: ['', ...CATEGORY_TYPE_OPTIONS.air] },
      { key: '檢測項目', label: '檢測項目', type: 'text' },
      { key: '檢測濃度/質量單位', label: '檢測濃度/質量單位', type: 'unitcode' },
      { key: '其他檢測濃度/質量單位', label: '其他檢測濃度/質量單位', type: 'text' },
      { key: '比較關係', label: '比較關係', type: 'suggest', options: COMPARE_SUGGESTIONS },
      { key: '檢測數值', label: '檢測數值', type: 'number' },
      { key: '檢測極限', label: '檢測極限', type: 'number' },
      { key: '檢測方法', label: '檢測方法', type: 'text' },
      { key: '檢測機構許可證號', label: '檢測機構許可證號', type: 'agencycode', required: true },
      { key: '其他檢測機構名稱', label: '其他檢測機構名稱', type: 'text' },
      { key: '備註', label: '備註', type: 'textarea' },
    ],
  },
  water: {
    key: 'water',
    label: '水質',
    sourceFile: '水質檢測資料填寫.xlsx',
    dataSheetName: '水質檢測項目',
    basicSheetName: '監測點基本資料',
    fields: [
      { key: '日期(起)', label: '日期(起)', type: 'date', required: true },
      { key: '時間(起)', label: '時間(起)', type: 'time' },
      { key: '日期(迄)', label: '日期(迄)', type: 'date' },
      { key: '時間(迄)', label: '時間(迄)', type: 'time' },
      { key: '採樣地點', label: '採樣地點', type: 'text' },
      { key: '座標系統', label: '座標系統', type: 'select', options: ['', '2', '3'],
        optionLabels: { '2': '2：WGS84', '3': '3：TWD97-TM2' } },
      { key: '採樣座標-經度 X', label: '採樣座標-經度 X', type: 'number' },
      { key: '採樣座標-緯度 Y', label: '採樣座標-緯度 Y', type: 'number' },
      { key: '採樣深度(公尺)', label: '採樣深度(公尺)', type: 'number' },
      { key: '採樣水深(公尺)', label: '採樣水深(公尺)', type: 'number' },
      { key: '管制編號', label: '管制編號', type: 'text' },
      { key: '檢測類別', label: '檢測類別', type: 'select', required: true, options: ['', ...CATEGORY_TYPE_OPTIONS.water] },
      { key: '檢測項目', label: '檢測項目', type: 'text' },
      { key: '檢測濃度/質量單位', label: '檢測濃度/質量單位', type: 'unitcode' },
      { key: '其他檢測濃度/質量單位', label: '其他檢測濃度/質量單位', type: 'text' },
      { key: '比較關係', label: '比較關係', type: 'suggest', options: COMPARE_SUGGESTIONS },
      { key: '檢測數值', label: '檢測數值', type: 'number' },
      { key: '檢測極限', label: '檢測極限', type: 'number' },
      { key: '檢測方法', label: '檢測方法', type: 'text' },
      { key: '檢測機構許可證號', label: '檢測機構許可證號', type: 'agencycode', required: true },
      { key: '其他檢測機構名稱', label: '其他檢測機構名稱', type: 'text' },
      { key: '備註', label: '備註', type: 'textarea' },
    ],
  },
  geo: {
    key: 'geo',
    label: '地質',
    sourceFile: '地質檢測資料填寫.xlsx',
    dataSheetName: '地質檢測項目',
    basicSheetName: '監測點基本資料',
    fields: [
      { key: '日期(起)', label: '日期(起)', type: 'date', required: true },
      { key: '時間(起)', label: '時間(起)', type: 'time' },
      { key: '日期(迄)', label: '日期(迄)', type: 'date' },
      { key: '時間(迄)', label: '時間(迄)', type: 'time' },
      { key: '採樣地點', label: '採樣地點', type: 'text' },
      { key: '座標系統', label: '座標系統', type: 'select', options: ['', '2', '3'],
        optionLabels: { '2': '2：WGS84', '3': '3：TWD97-TM2' } },
      { key: '採樣座標-經度 X', label: '採樣座標-經度 X', type: 'number' },
      { key: '採樣座標-緯度 Y', label: '採樣座標-緯度 Y', type: 'number' },
      { key: '採樣深度(公尺)', label: '採樣深度(公尺)', type: 'number' },
      { key: '管制編號', label: '管制編號', type: 'text' },
      { key: '檢測類別', label: '檢測類別', type: 'select', required: true, options: ['', ...CATEGORY_TYPE_OPTIONS.geo] },
      { key: '檢測項目', label: '檢測項目', type: 'text' },
      { key: '檢測濃度/質量單位', label: '檢測濃度/質量單位', type: 'unitcode' },
      { key: '其他檢測濃度/質量單位', label: '其他檢測濃度/質量單位', type: 'text' },
      { key: '比較關係', label: '比較關係', type: 'suggest', options: COMPARE_SUGGESTIONS },
      { key: '檢測數值', label: '檢測數值', type: 'number' },
      { key: '檢測極限', label: '檢測極限', type: 'number' },
      { key: '檢測方法', label: '檢測方法', type: 'text' },
      { key: '檢測機構許可證號', label: '檢測機構許可證號', type: 'agencycode', required: true },
      { key: '其他檢測機構名稱', label: '其他檢測機構名稱', type: 'text' },
      { key: '備註', label: '備註', type: 'textarea' },
    ],
  },
  noise: {
    key: 'noise',
    label: '噪音',
    sourceFile: '噪音監測資料填寫.xlsx',
    dataSheetName: '噪音檢測項目',
    basicSheetName: '監測點基本資料',
    fields: [
      { key: '日期(起)', label: '日期(起)', type: 'date', required: true },
      { key: '時間(起)', label: '時間(起)', type: 'time' },
      { key: '日期(迄)', label: '日期(迄)', type: 'date' },
      { key: '時間(迄)', label: '時間(迄)', type: 'time' },
      { key: '監測地點', label: '監測地點', type: 'text' },
      { key: '座標系統', label: '座標系統', type: 'select', options: ['', '2', '3'],
        optionLabels: { '2': '2：WGS84', '3': '3：TWD97-TM2' } },
      { key: '採樣座標-經度 X', label: '採樣座標-經度 X', type: 'number' },
      { key: '採樣座標-緯度 Y', label: '採樣座標-緯度 Y', type: 'number' },
      { key: '管制標準', label: '管制標準', type: 'select', options: ['', '工廠（場）噪音', '營建工程', '娛樂場所/營業場所', '擴音設施', '其他-1', '其他-2', '噪音管制法第7條第1項', '噪音管制法第15條第3項', '噪音管制法第14條第2項', '無'] },
      { key: '管制區', label: '管制區', type: 'select', options: ['', '第1類', '第2類', '第3類', '第4類', '無'] },
      { key: '環境音量標準', label: '環境音量標準', type: 'select', options: ['', '0', '1', '2'],
        optionLabels: { '0': '0-不適用', '1': '1-緊鄰未滿八公尺之道路', '2': '2-緊鄰八公尺以上之道路' } },
      { key: '頻率範圍', label: '頻率範圍', type: 'select', options: ['', '20 Hz 至 200 Hz', '20 Hz 至 20kHz'] },
      { key: '音源發聲特性', label: '音源發聲特性', type: 'select', options: ['', '最大音量(Lmax)', '均能音量(Leq)', '均能音量(Leq,LF)', '最大振動位準(Lvmax)', '事件振動位準(Lveq)', 'Lvd(10)', 'Lvn(10)'] },
      { key: '檢測類別', label: '檢測類別', type: 'select', required: true, options: ['', ...CATEGORY_TYPE_OPTIONS.noise] },
      { key: '監測時段', label: '監測時段', type: 'select', options: ['', '日間', '晚間', '夜間', '全天'] },
      { key: '監測數值', label: '監測數值', type: 'number' },
      { key: '監測單位', label: '監測單位', type: 'unitcode' },
      { key: '其他監測單位', label: '其他監測單位', type: 'text' },
      { key: '監測方法', label: '監測方法', type: 'text' },
      { key: '檢測機構許可證號', label: '檢測機構許可證號', type: 'agencycode', required: true },
      { key: '其他檢測機構名稱', label: '其他檢測機構名稱', type: 'text' },
      { key: '備註', label: '備註', type: 'textarea' },
    ],
  },
  eco: {
    key: 'eco',
    label: '生態',
    sourceFile: '生態調查資料填寫.xlsx',
    dataSheetName: '生態檢測項目',
    basicSheetName: '監測點基本資料',
    fields: [
      { key: '日期(起)', label: '日期(起)', type: 'date', required: true },
      { key: '時間(起)', label: '時間(起)', type: 'time' },
      { key: '日期(迄)', label: '日期(迄)', type: 'date' },
      { key: '時間(迄)', label: '時間(迄)', type: 'time' },
      { key: '調查地點', label: '調查地點', type: 'text' },
      { key: '座標系統', label: '座標系統', type: 'select', options: ['', '2', '3'],
        optionLabels: { '2': '2：WGS84', '3': '3：TWD97-TM2' } },
      { key: '採樣座標-經度 X', label: '採樣座標-經度 X', type: 'number' },
      { key: '採樣座標-緯度 Y', label: '採樣座標-緯度 Y', type: 'number' },
      { key: '調查項目', label: '調查項目', type: 'text' },
      { key: '調查頻率', label: '調查頻率', type: 'text' },
      { key: '環境現況描述', label: '環境現況描述', type: 'textarea' },
      { key: '學名', label: '學名', type: 'text' },
      { key: '中文名', label: '中文名', type: 'text' },
      { key: '數量', label: '數量', type: 'text' },
      { key: '特有性', label: '特有性', type: 'select', options: ['', '特有種', '特有亞種'] },
      { key: '保育分類', label: '保育分類', type: 'select', options: ['', 'I', 'II', 'III'] },
      { key: '調查方法描述', label: '調查方法描述', type: 'textarea', required: true },
      { key: '檢測機構許可證號', label: '檢測機構許可證號', type: 'agencycode', required: true },
      { key: '其他檢測機構名稱', label: '其他檢測機構名稱', type: 'text' },
      { key: '備註', label: '備註', type: 'textarea' },
    ],
  },
};

const CATEGORY_ORDER = ['air', 'water', 'geo', 'noise', 'eco'];
